Repository lorraine98/good-fight, pull requests merged in 2022-04, with the labels that each got.

#20 Feat/#12 : Home 페이지 제작
  .eslintrc.json
  next.config.js
  package.json
  src/components/Header.tsx
  src/components/Layout.tsx
  src/components/NavBar.tsx
  src/pages/_app.tsx
  src/pages/home/components/Banner.tsx
  src/pages/home/components/Board.tsx
  src/pages/home/components/Photo.tsx
  src/pages/home/components/RecentFightBox.tsx
  src/pages/home/index.tsx
  src/shared/components/MyFightsStatusIcon/index.tsx
  static/adv.jpg
  static/test.jpg
  tsconfig.json
Labels: Feature, Chore

#21 Feat/#18 니쌈 폼 만들기
  package.json
  src/api/post-your-fights-form.tsx
  src/components/Header.tsx
  src/pages/my-fights/add-form.tsx
  src/pages/my-fights/add.tsx
  src/pages/my-fights/index.tsx
  src/pages/your-fights/add-form.tsx
  src/pages/your-fights/index.tsx
  src/shared/components/form-input/index.tsx
  src/shared/form-select/index.tsx
  src/styles/globals.css
  yarn.lock
Labels: Feature

#24 Feat/#19 로그인 새로고침 오류 해결
  package.json
  src/api/auth-google-login.tsx
  src/pages/auth/hook/useAuth.tsx
  src/pages/auth/index.tsx
  src/route/PrivateRoute.tsx
  src/shared/components/button/index.tsx
  yarn.lock
Labels: Fix

#25 Feat/#22
  .babelrc
  next.config.js
  package.json
  src/api/get-random-nickname.tsx
  src/api/get-your-fights.tsx
  src/components/Header.tsx
  src/components/Layout.tsx
  src/components/NavBar.tsx
  src/pages/_app.tsx
  src/pages/auth/index.tsx
  src/pages/home/components/Board.tsx
  src/pages/home/components/Photo.tsx
  src/pages/home/components/RecentFightBox.tsx
  src/pages/your-fights/components/NissamBoard.tsx
  src/pages/your-fights/components/OrderBy.tsx
  src/pages/your-fights/index.tsx
  src/setupProxy.js
  src/shared/components/MyFightsStatusIcon/index.tsx
  src/shared/components/add-button/index.tsx
  src/shared/components/button/index.tsx
  src/styles/theme.ts
  yarn.lock
Labels: Feature

#30 Feat/#28 홈페이지에 내쌈 api 연동
  src/api/auth-google-login.tsx
  src/api/my-fights.tsx
  src/pages/home/components/Board.tsx
  src/pages/home/index.tsx
  src/pages/my-fights/add-form.tsx
  src/pages/my-fights/api/delete-my-fights-data.tsx
  src/pages/my-fights/api/get-my-fights-data.tsx
  src/pages/my-fights/api/post-my-fights-data.tsx
  src/pages/my-fights/api/update-my-fights-data.tsx
  src/pages/my-fights/index.tsx
  src/pages/my-fights/update-form.tsx
Labels: Feature

#31 Feat/#22
  package.json
  src/api/get-your-fights.tsx
  src/api/post-your-fights-form.tsx
  src/api/your-fights.tsx
  src/components/Header.tsx
  src/components/NavBar.tsx
  src/pages/my-fights/update-form.tsx
  src/pages/your-fights/add-form.tsx
  src/pages/your-fights/components/NissamBoard.tsx
  src/pages/your-fights/components/OrderByHeader.tsx
  src/pages/your-fights/components/YourFightsBoard.tsx
  src/pages/your-fights/index.tsx
  src/shared/components/MyFightsStatusIcon/index.tsx
  src/shared/components/ThumbsDownIcon/index.tsx
  src/shared/components/ThumbsUpIcon/index.tsx
  src/shared/components/add-button/index.tsx
  src/shared/form-select/index.tsx
  src/shared/functions/DateFormat/index.tsx
  src/styles/theme.ts
  tsconfig.json
  yarn.lock
Labels: Feature, Fix, Refactor
