Repository lorraine98/good-fight, pull requests merged in 2022-03, with the labels that each got.

#6 Feat/#4/component
  package.json
  src/components/Header.tsx
  src/components/Layout.tsx
  src/components/NavBar.tsx
  src/pages/404.tsx
  src/pages/_app.tsx
  src/pages/_document.tsx
  src/pages/index.tsx
  src/pages/my-fights/index.tsx
  src/pages/my-page/index.tsx
  src/pages/your-fights/index.tsx
  src/styles/globals.css
  yarn.lock
Labels: Feature, Refactor

#9 chore: prettierrc 추가 및 navbar 카테고리 정렬
  .prettierrc
  next.config.js
  src/components/Header.tsx
  src/components/Layout.tsx
  src/components/NavBar.tsx
  src/pages/404.tsx
  src/pages/_app.tsx
  src/pages/_document.tsx
  src/pages/index.tsx
  src/styles/globals.css
Labels: Chore

#10 Feat/#5 Add theme
  package.json
  src/components/Header.tsx
  src/components/Layout.tsx
  src/components/NavBar.tsx
  src/pages/_app.tsx
  src/pages/_document.tsx
  src/styles/emotion.d.ts
  src/styles/globals.css
  src/styles/theme.ts
  static/favicon.ico
  tsconfig.json
  yarn.lock
Labels: Feature, Style

#13 Feat/#11 Make firebase login
  .gitignore
  src/atoms/user.ts
  src/components/Header.tsx
  src/components/Layout.tsx
  src/components/NavBar.tsx
  src/pages/_app.tsx
  src/pages/auth/api/auth-google-login.tsx
  src/pages/auth/index.tsx
  src/route/PrivateRoute.tsx
  src/shared/FireBase.tsx
  src/shared/components/button/index.tsx
  src/shared/components/container/index.tsx
  src/shared/img/logo.png
Labels: Feature

#15 Feat/#14 change emtion theme to mui theme
  src/components/Header.tsx
  src/components/Layout.tsx
  src/components/NavBar.tsx
  src/pages/_app.tsx
  src/pages/auth/index.tsx
  src/shared/components/button/index.tsx
  src/styles/emotion.d.ts
  src/styles/theme.ts
Labels: Feature

#17 Feat/#16 내쌈 폼 만들기
  package.json
  public/favicon.ico
  src/api/auth-google-login.tsx
  src/api/post-my-fights-form.tsx
  src/pages/auth/index.tsx
  src/pages/my-fights/add.tsx
  src/pages/my-fights/index.tsx
  src/shared/FireBase.tsx
  src/shared/components/add-button/index.tsx
  src/styles/globals.css
  yarn.lock
Labels: Feature
